# Generated by Django 3.1.2 on 2021-01-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210103_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='spotify_id',
            field=models.CharField(max_length=22),
        ),
    ]
