# Generated by Django 3.1.2 on 2021-01-05 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_useractivity_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 9, 17, 12, 478251, tzinfo=utc)),
        ),
    ]
